name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          repository: MindfulMichaelJames/star-wars
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Frontend Dependencies
        run: |
          cd star-wars  # Navigate to the frontend directory within the cloned repository
          yarn install

      - name: Build Frontend Application
        run: |
          cd star-wars  # Navigate to the frontend directory within the cloned repository
          yarn build

      - name: Start Frontend Application
        run: |
          cd star-wars  # Navigate to the frontend directory within the cloned repository
          yarn start &

          # Wait for the application to start (adjust as needed)
          timeout 30s bash -c 'until curl -sf http://localhost:3000; do sleep 1; done'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Tests
        run: |
          python path/to/your/test_script.py  # Execute Selenium tests

