name: Clone and Start Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Clone Public Repository
        run: |
          git clone https://github.com/MindfulMichaelJames/star-wars frontend
          cd frontend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.2.0'

      - name: Install Dependencies
        run: |
          cd frontend
          yarn install

      - name: Build Project
        run: |
          cd frontend
          yarn build

      - name: Start Project
        run: |
          cd frontend
          yarn start &
          echo "Waiting for the application to start..."
          timeout 60s bash -c 'until curl -sf http://localhost:3000; do sleep 1; done'

      - name: Run Tests
        run: |
          cd frontend
          # Add commands here to run your tests against the running project

